// Code generated by "stringer -type=FlowEvent"; DO NOT EDIT.

package flow

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Back-0]
	_ = x[ToBotNameSetting-1]
	_ = x[BotNameSet-2]
	_ = x[ToSpeakerNameSetting-3]
	_ = x[SpeakerNameSet-4]
}

const _FlowEvent_name = "BackToBotNameSettingBotNameSetToSpeakerNameSettingSpeakerNameSet"

var _FlowEvent_index = [...]uint8{0, 4, 20, 30, 50, 64}

func (i FlowEvent) String() string {
	if i < 0 || i >= FlowEvent(len(_FlowEvent_index)-1) {
		return "FlowEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FlowEvent_name[_FlowEvent_index[i]:_FlowEvent_index[i+1]]
}
