// Code generated by "stringer -type=FlowState"; DO NOT EDIT.

package flow

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Default-0]
	_ = x[SettingBotName-1]
	_ = x[SettingSpeakerName-2]
}

const _FlowState_name = "DefaultSettingBotNameSettingSpeakerName"

var _FlowState_index = [...]uint8{0, 7, 21, 39}

func (i FlowState) String() string {
	if i < 0 || i >= FlowState(len(_FlowState_index)-1) {
		return "FlowState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FlowState_name[_FlowState_index[i]:_FlowState_index[i+1]]
}
